<?=$this->doctype();?>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
    <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
        <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
            <!--[if (gte IE 9)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
                <head>

                    <!-- Basic Page Needs
                    ================================================== -->
                    <meta charset="utf-8">
                    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

                    <title>Harness Media Group + Building Brand Experiences</title>
                    <meta name="Title" content="Harness Media Group - Building Brand Experiences" />
                    <meta name="Author" content="www.harnessmedia.com" />
                    <meta name="Subject" content="Identity Design, Branding, High Quality Design, Graphic Design, Design, Web Design, Print Design, Marketing, Strtegic Marketing." />
                    <meta name="Description" content="Harness Media Group - Building Brand Experiences. Identity Design, Branding, User Experience, e-commerce, ecommerce, Action Sports ecommerce, Usability, High Quality Design, Graphic Design, Design, Web Design, Print Design, Marketing, Strtegic Marketing. " />
                    <meta name="Keywords" content="Identity Design, Branding, User Experience, e-commerce, ecommerce, Action Sports ecommerce, Usability, High Quality Design, Graphic Design, Design, Web Design, Print Design, Marketing, Strtegic Marketing, Jacin Greenhill, DC, District of Columbia, Newport Beach, California, NYC, New York City, Virginia Beach, VA Beach, Alabama, Sheffield" />


                    <!-- Mobile Specific Metas
                    ================================================== -->
                    <meta name="viewport" content="width=device-width,initial-scale=1">


                    <!-- CSS concatenated and minified via ant build script
                    ================================================== -->
                    <link rel="stylesheet" href="css/base.css">
                    <link rel="stylesheet" href="css/skeleton.css">
                    <link rel="stylesheet" href="css/layout.css">
                    <link rel="stylesheet" href="css/style.css">  

                    <!-- Favicons
                    ================================================== -->
                    <link rel="shortcut icon" href="images/favicon.ico">
                    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
                    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
                    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">


                    <script src="js/libs/modernizr-2.0.6.min.js"></script>
                </head>

                <body>

                    <!-- Primary Page Layout
                    ================================================== -->
                    <div id="container" class="container">
                        <header class="seventeen columns alpha default"> 

                        <div id="logo" class="two column alpha sprite">
                            <a href="#">
                                Harness Media Group
                            </a>
                        </div>

                        <nav class="ten column">
                        <ul id="nav-primary" role="navigation">
                            <li><a href="work.php">Work</a></li>     
                            <li><a href="play.php">Play</a></li>     
                            <li><a href="services.php">Serve</a></li>     
                            <li><a href="connect.php" class="selected">Connect</a></li>      
                            <li><a href="about.php">About</a></li>
                        </ul>
                        </nav>

                        <a href="design-quantified.php" class="three columns" id="learnmore">
                            <img src="img/learn-more-design-quantified.png" alt="Design Quantified" name="learnmore" width="214" height="49">
                        </a>
                        </header>

                        <div id="main" role="main" class="seventeen columns">
                            <div class="page-title">
                                <img src="img/title-about.png" />
                            </div>
                            <a href="<?=$this->url(array('controller'=>'work', 'title'=>$this->title), null, true);?>">Do Work son</a>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p>
                            <a href="/connect/get-a-quote.php" class="get-a-quote"><img src="img/button-get-a-quote.jpg" /></a>
                        </div>

                        <footer id="footer" class="seventeen columns">
                        <div class="row">
                            <section id="blog-entries" class="one-third column alpha">
                            <hgroup>
                            <h1>MARKETING</h1>
                            <h2>INSIGHTS</h2>
                            </hgroup>
                            <ul>
                                <li><a href="#">Ecommerce<span class="arrow"></span></a></li>
                                <li><a href="#">Social Media</a></li>
                                <li><a href="#">Email Marketing</a></li>
                                <li><a href="#">SEO/SEM</a></li>
                                <li><a href="#">Landing Pages 2</a></li>
                            </ul>
                            </section>
                            <section id="facebook-module" class="one-third column">
                            <div class="fb-like-box" data-href="https://www.facebook.com/pages/Rossi-Valentino/50801001459" data-width="310" 
                                data-height="250" data-show-faces="true" data-border-color="white" data-stream="true" data-header="false"></div>
                            </section>
                            <section id="email-signup" class="one-third column omega">

                            <form id="form-newsletter" method="post">
                                <fieldset id="email-set">
                                    <label>Email</label>
                                    <input type="text" name="email" />
                                </fieldset>

                                <fieldset id="name-set">
                                    <label>First Name</label>
                                    <input type="text" name="firstname" />
                                </fieldset>

                                <fieldset id="gender-set">
                                    <label for="">Gender</label>
                                    <div class="radio-container">
                                        <label for="male-radio"><input type="radio" name="gender" id="male-radio" value="male" /> 
                                            <span>Male</span>
                                        </label>
                                        <label for="female-radio"><input type="radio" name="gender" id="female-radio" value="female" /> 
                                            <span>Female</span>
                                        </label>
                                    </div>
                                </fieldset>
                                <button type="submit" id="button-submit">Submit!</button>

                            </form>

                            </section>
                        </div>

                        <div class="row">
                            <section id="description" class="twelve columns alpha">
                            <div id="detail">
                                <strong>Harness Media Group</strong> (HMG) is a digital collective that creates deliberate yet provoking ideas for youth culture in the online marketplace. Clients include La Jolla Group/O'Neill, Killer Dana, Skateboards.com, Metal Mulisha, Lost, Nestle, XFX, Nike, Rusty and more. Harness Media Group is based in New York City and Orange County, CA, two of the primary hubs for both fashion and youth culture in the United States... sent from my iPhone. Please excuse any typos, yo!
                            </div>
                            <div id="copyright">
                                &copy; Harness Media Group Inc. All rights reserved.
                            </div>
                            </section>
                            <nav class="three columns">
                            <ul id="nav-secondary" role="navigation">
                                <li><a href="work.php">WORK</a></li>     
                                <li><a href="process.php">PROCESS</a></li>     
                                <li><a href="services.php">SERVICES</a></li>     
                                <li><a href="about.php">ABOUT</a></li>      
                                <li><a href="connect.php">CONNECT</a></li>
                                <li><a href="#">H/MG FACEBOOK</a></li>
                            </ul>
                            </nav>
                            <section id="footer-logo" class="one column omega"></section>
                        </div>
                        </footer>
                    </div> <!--! end of #container -->

                    <!-- JS
                    ================================================== -->
                    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
                    <script>window.jQuery || document.write('<script src="js/libs/jquery-1.6.2.min.js"><\/script>')</script>


                        <script defer src="js/plugins.js"></script>
                        <script defer src="js/script.js"></script>

                        <div id="fb-root"></div>
                        <script>(function(d, s, id) {
                            var js, fjs = d.getElementsByTagName(s)[0];
                            if (d.getElementById(id)) return;
                            js = d.createElement(s); js.id = id;
                            js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=119524864801317";
                            fjs.parentNode.insertBefore(js, fjs);
                            }(document, 'script', 'facebook-jssdk'));</script>

                        <!-- font replacement -->
                        <script src="js/libs/cufon-yui.js" type="text/javascript"></script>
                        <script src="js/libs/Avenir_400-Avenir_900.font.js" type="text/javascript"></script>
                        <script type="text/javascript">		
                            Cufon.replace('#nav-primary li,#blog-entries h1,#blog-entries h2,#blog-entries li,button,#button-submit', {hover: true});
                            </script>
                            <script type="text/javascript"> Cufon.now(); </script>

                            <!-- Google Analytics
                            <script>
                                window._gaq = [['_setAccount','UA-1556134-1'],['_trackPageview'],['_trackPageLoadTime']];
                                Modernizr.load({
                                load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
                                });
                            </script>
                            -->

                            <!--[if lt IE 7 ]>
                            <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
                            <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
                            <![endif]-->

                            <!-- End Document
                            ================================================== -->  
                        </body>
                    </html>
