
<ul id="work-nav">
    <li><a href="#">WEB/DIGITAL</a></li>
    <li><a href="#" class="active">IDENTITY</a></li>
    <li><a href="#">VIDEO</a></li>
    <li><a href="#">PRINT</a></li>
</ul>
<div id="view-content">
    <ul class="thumbs">
        <li><a href="#">Nike/Hurley: USOPEN 2012</a></li>
        <li><a href="#">ONEILL</a></li>
        <li><a href="#">TLFI</a></li>
        <li><a href="#">KILLERDANA</a></li>
        <li><a href="#">CONTIKI</a></li>
        <li><a href="#">FMF</a></li>
        <li><a href="#">Skateboards</a></li>
    </ul>
</div>

<script type="text/template" id="template-work-overlay">
    <div id="overlay">
        <div id="bg">
            <span id="close">X</span>

            <img src="img/work-fpo.png" alt="fpo" />

            <h2>THE PROJECT TITLE</h2>

            <ul id="project-thumbs">
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>

            <p>Short description goes here and should be very descriptive of the overall project. Two to 3 sentences max.</p>

            <p><strong>Tech:</strong></p>

            <p>FRY E-Commerce Endecea Scene7 Gomez WordPress Omniture/SiteCatalyst Google Analytics</p>
        </div>
    </div>
</script>
