<ul id="work-nav">
    <li><a href="#">WEB/DIGITAL</a></li>
    <li><a href="#" class="active">IDENTITY</a></li>
    <li><a href="#">VIDEO</a></li>
    <li><a href="#">PRINT</a></li>
</ul>
<div id="view-content">
    <ul class="thumbs">
        <?= $this->thumbnailHTML; ?>
    </ul>
</div>

<script type="text/javascript" charset="utf-8">
    var HMG = {};
    HMG.data = <? echo json_encode($this->data); ?>
</script>

<script type="text/template" id="template-work-overlay">
<div id="work-overlay">
    <div id="bg">
        <div id="work-content">
            <nav role="work" id="nav-work">
                <ul>
                    <li><a href="#"><img src="/img/arrow-left.png" alt="Prev" /> Prev</a></li>
                    <li>|</li>
                    <li><a href="#">Next <img src="/img/arrow-right.png" alt="" /></a></li>
                    <li><a href="#" id="close">X</a></li>
                </ul>
            </nav>
           
            <img id="pic-main" src="img/work-fpo.png" alt="fpo" />

            <h2>{{=it.title}}</h2>

            <ul id="project-thumbs">
                {{~it.pictures :value:index}}
                <li><img src="{{=value}}" /></li>
                {{~}}
            </ul>

            <p id="description">{{=it.description}}</p>

            <p><strong>Tech:</strong></p>
            <ul id="services">
                {{~it.services :value:index}}
                <li>{{=value}}</li>
                {{~}}
            </ul>

        </div>
    </div>
</div>
</script>
