<div id="view-content">
	<p>Harness Media Group is a multidisciplinary creative team that lives and breathes (between the color=filled pixels of creative data) in the color-filled combination of the creative application of design and data. We believe there is a innate responsibility for creative to not only be relevant but results-driven, therefore bridging the gap of creative intelligence.</p>
</div>
