                        <footer id="footer" class="seventeen columns">
                        <?=$this->showSocial ? $this->socialBoxes : ''; ?>

                        <div class="row">
                            <section id="description" class="twelve columns alpha">
                            <div id="detail">
                                <strong>Harness Media Group</strong> (HMG) is a digital collective that creates deliberate yet provoking ideas for youth culture in the online marketplace. Clients include La Jolla Group/O'Neill, Killer Dana, Skateboards.com, Metal Mulisha, Lost, Nestle, XFX, Nike, Rusty and more. Harness Media Group is based in New York City and Orange County, CA, two of the primary hubs for both fashion and youth culture in the United States... sent from my iPhone. Please excuse any typos, yo!
                            </div>
                            <div id="copyright">
                                &copy; Harness Media Group Inc. All rights reserved.
                            </div>
                            </section>
                            <nav class="three columns">
                            <?=$this->footerNav;?>
                            </nav>
                            <section id="footer-logo" class="one column omega"></section>
                        </div>
                        </footer>
 
