                    <!-- JS
                    ================================================== -->
                    <script>window.jQuery || document.write('<script src="js/libs/jquery-1.8.0.min.js"><\/script>')</script>


                        <script defer src="js/plugins.js"></script>
                        <script defer src="js/script.js"></script>

                        <div id="fb-root"></div>
                        <script>(function(d, s, id) {
                            var js, fjs = d.getElementsByTagName(s)[0];
                            if (d.getElementById(id)) return;
                            js = d.createElement(s); js.id = id;
                            js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=119524864801317";
                            fjs.parentNode.insertBefore(js, fjs);
                            }(document, 'script', 'facebook-jssdk'));</script>

                        <!-- font replacement -->
                        <script src="js/libs/cufon-yui.js" type="text/javascript"></script>
                        <script src="js/libs/Avenir_400-Avenir_900.font.js" type="text/javascript"></script>
                        <script type="text/javascript">		
                            Cufon.replace('#nav-menu-button,.nav-primary li,#blog-entries h1,#blog-entries h2,#blog-entries li,button,#button-submit,.numbers li, #work-nav', {hover: true});
                            </script>
                            <script type="text/javascript"> Cufon.now(); </script>

                            <!-- Google Analytics
                            <script>
                                window._gaq = [['_setAccount','UA-1556134-1'],['_trackPageview'],['_trackPageLoadTime']];
                                Modernizr.load({
                                load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
                                });
                            </script>
                            -->

                            <!--[if lt IE 7 ]>
                            <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
                            <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
                            <![endif]-->
