                        <header class="seventeen columns alpha">

                        <div id="header">

                            <div id="logo" class="two column alpha sprite">
                                <a href="<?=$this->baseUrl;?>index">
                                    Harness Media Group
                                </a>
                            </div>

                            <nav class="ten column">
                            <span id="nav-menu-button"><a href="#">Menu</a></span>
                            <ul id="nav-primary" role="navigation">
                                <li><a href="<?=$this->baseUrl;?>work">Work</a></li>     
                                <li><a href="<?=$this->baseUrl;?>play">Play</a></li>     
                                <li><a href="<?=$this->baseUrl;?>serve">Serve</a></li>     
                                <li><a href="<?=$this->baseUrl;?>connect">Connect</a></li>      
                                <li><a href="<?=$this->baseUrl;?>about">About</a></li>
                            </ul>
                            </nav>

                            <a href="<?=$this->baseUrl;?>design-quantified" class="three columns" id="learnmore">
                                <img src="<?=$this->baseUrl;?>img/learn-more-design-quantified.png" alt="Design Quantified" name="learnmore" width="214" height="49">
                            </a>

                        </div>

                        </header>

