                        <header class="seventeen columns alpha">

                        <div id="header">

                            <div id="logo" class="two column alpha sprite">
                                <a href="#">
                                    Harness Media Group
                                </a>
                            </div>

                            <nav class="ten column">
                            <span id="nav-menu-button"><a href="#">Menu</a></span>
                            <ul id="nav-primary" role="navigation">
                                <li><a href="/work">Work</a></li>     
                                <li><a href="/play">Play</a></li>     
                                <li><a href="/serve">Serve</a></li>     
                                <li><a href="/connect">Connect</a></li>      
                                <li><a href="/about">About</a></li>
                            </ul>
                            </nav>

                            <a href="design-quantified.php" class="three columns" id="learnmore">
                                <img src="img/learn-more-design-quantified.png" alt="Design Quantified" name="learnmore" width="214" height="49">
                            </a>

                        </div>

                        </header>

