<?php 
echo $this->doctype();

$fc = Zend_Controller_Front::getInstance();
$controller = $fc->getRequest()->getControllerName();

// sets title image
$titleUrl = "img/title-$controller.png";

// sets nav options
$options = array(
    'maxDepth' => 0,
    'ulClass' => 'nav-primary'
);
$this->navigation()->findByUri($controller)->setActive(true);
?>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
                <head>

                    <!-- Basic Page Needs
                    ================================================== -->
                    <?= $this->headMeta(); ?>
                    <?= $this->headTitle(); ?>

                    <!-- Mobile Specific Metas
                    ================================================== -->

                    <!-- CSS concatenated and minified via ant build script
                    ================================================== -->
                    <?= $this->headLink(); ?>
                    <?= $this->headScript(); ?>


                    <!-- Favicons
                    ================================================== -->
                    <link rel="shortcut icon" href="<?=$this->baseUrl;?>images/favicon.ico">
                    <link rel="apple-touch-icon" href="<?=$this->baseUrl?>images/apple-touch-icon.png">
                    <link rel="apple-touch-icon" sizes="72x72" href="<?=$this->baseUrl;?>images/apple-touch-icon-72x72.png">
                    <link rel="apple-touch-icon" sizes="114x114" href="<?=$this->baseUrl;?>images/apple-touch-icon-114x114.png">

                </head>

                <body class="default">

                    <!-- Primary Page Layout
                    ================================================== -->
                    
                    <div id="container" class="container">
                        <?php 
                            echo $this->partial('_header.phtml', array(
                            'controller' => $controller,
                            'navigation' => $this->navigation()->menu()->renderMenu($this->container, $options)
                            )); 
                        ?>

                        <div id="main" role="main" class="seventeen columns">

                            <div class="page-title">
                                <?php if(file_exists($titleUrl)) { echo "<img src='$this->baseUrl$titleUrl' />"; } ?>
                            </div>
                            <?= $this->layout()->content; ?>
                            <a href="<?=$this->baseUrl;?>get-a-quote" class="get-a-quote"><img src="<?=$this->baseUrl;?>img/button-get-a-quote.jpg" /></a>

                        </div> <!-- #main -->

                        <?= $this->render('_footer.phtml'); ?>

                    </div> <!-- #container -->

                    <?= $this->render('_footer-scripts.phtml'); ?>

                    <!-- End Document
                    ================================================== -->  

                    </body>
                </html>
