<div class="slideshow">
    <ul class="slides">
        <li><a href="#"><img src="<?=$this->baseUrl;?>img/slide-1.jpg" alt="Harness Media Group" /></a></li>
        <li><a href="#"><img src="<?=$this->baseUrl;?>img/slide-2.jpg" alt="Harness Media Group" /></a></li>
        <li><a href="#"><img src="<?=$this->baseUrl;?>img/slide-3.jpg" alt="Harness Media Group" /></a></li>
        <li><a href="#"><img src="<?=$this->baseUrl;?>img/slide-4.jpg" alt="Harness Media Group" /></a></li>
    </ul>
</div>
