<div class="slideshow">
    <ul class="numbers">
        <li data-id="1" class="selected">1</li>
        <li data-id="2">2</li>
        <li data-id="3">3</li>
        <li data-id="4">4</li>
    </ul>
    <ul class="slides">
        <li data-id="1"><a href="#"><img src="<?=$this->baseUrl;?>img/slide-1.jpg" alt="Harness Media Group" /></a></li>
        <li data-id="2"><a href="#"><img src="<?=$this->baseUrl;?>img/slide-2.jpg" alt="Harness Media Group" /></a></li>
        <li data-id="3"><a href="#"><img src="<?=$this->baseUrl;?>img/slide-3.jpg" alt="Harness Media Group" /></a></li>
        <li data-id="4"><a href="#"><img src="<?=$this->baseUrl;?>img/slide-4.jpg" alt="Harness Media Group" /></a></li>
    </ul>
</div>
