<div id="view-content">
    <p>We are selective in projects that make it through the door because of one key factor - time is our most valuable commodity. With this in mind, we buy up every opportunity to serve where our passions are and where life-altering purpose can be found. That’s not to say that we don’t take on a ton of fun projects or projects that pay the bills ‘round here, just that we live in the moment while planning ahead and taking stock of past experiences that collectively help shape the future.</p> 
    <p>As the motto goes, WORK HARD / SERVE HARDER.</p> 
    <p>Here are a few causes we are passionate about: </p>
</div>
